{{- if and .Values.persistence.profiles.enabled (not .Values.persistence.profiles.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "livellm-browser.profilesPvcName" . }}
  labels:
    {{- include "livellm-browser.labels" . | nindent 4 }}
    app.kubernetes.io/component: profiles
spec:
  accessModes:
    - {{ .Values.persistence.profiles.accessMode }}
  {{- if .Values.persistence.profiles.storageClass }}
  storageClassName: {{ .Values.persistence.profiles.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.profiles.size }}
{{- end }}
